spring.datasource.url=jdbc:postgresql://dpg-d7hcfkpj2pic73a6h3qg-a:5432/cinema_o58u
spring.datasource.username=cinema_user
spring.datasource.password=o04WlXUdPLXK9Jq5gJaavXMgn4MPfrEz
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}